export const PLACES = [
    {
        id: '202',
        type: 'place',
        name: 'Porão do Jazz',
        vibe: 'Melancolia',
        heat: 'Morno',
        image: 'https://images.unsplash.com/photo-1514525253440-b393452e8d26?q=80&w=800',
        category: 'Local / Santuário',
        address: 'Centro Histórico, Curitiba - PR',
        description: 'Ambiente intimista com jazz noir, luz baixa e carta especial de drinks.',
        nextEvent: 'Sexta-feira • 22:00',
        capacity: 180,
        lat: -25.4284,
        lng: -49.2733,
    },
    {
        id: '204',
        type: 'place',
        name: 'Inferno Club',
        vibe: 'Euforia',
        heat: 'Ardendo',
        image: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?q=80&w=800',
        category: 'Casa de Show',
        address: 'Rua das Brasas, 147 - Curitiba - PR',
        description: 'Pista intensa, line-up pesado e noites de alta energia.',
        nextEvent: 'Sábado • 23:30',
        capacity: 420,
        lat: -25.4354,
        lng: -49.2713,
    },
    {
        id: '301',
        type: 'place',
        name: 'Teatro das Sombras',
        vibe: 'Sombras',
        heat: 'Frio',
        image: 'https://images.unsplash.com/photo-1503095392237-fc70339a2881?q=80&w=800',
        category: 'Teatro',
        address: 'Alameda das Máscaras, 90 - Curitiba - PR',
        description: 'Espaço para peças experimentais e performances autorais.',
        nextEvent: 'Domingo • 20:00',
        capacity: 260,
        lat: -25.44,
        lng: -49.28,
    },
];